name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        RDS_HOSTNAME: ${{ secrets.DB_HOST }}
        RDS_DB_NAME: ${{ secrets.DB_NAME }}
        RDS_PASSWORD: ${{ secrets.DB_PASSWORD }}
        RDS_PORT: ${{ secrets.DB_PORT }}
        RDS_USERNAME: ${{ secrets.DB_USER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py test